### PR TITLE
PAY-1087 Add a create_order method to the NuveiAchGateway in our lexop/active_merchant repo

### PR DESCRIPTION
**Pull request by patrickclery**
https://lexop.atlassian.net/browse/PAY-1087

### CODE REVIEW

**Review by VergunDA — CHANGES_REQUESTED** [review]
@patrickclery It is not clear for me why you created dedicated gateway for Nuvei Ach. It is just client that is responsible for communication with Nuvei API. It already exists [here](https://github.com/Lexop/lexop/blob/develop/lib/active_merchant/billing/nuvei_gateway.rb) and it implements the most methods from this NuveiACH gateway. Also I'm not sure that we have to test it separately. as it covers by operation testing using cassettes.
I'm sure that createOrder should be in NuveiGateway.

**Comment by patrickclery** [comment]
I did this before you started yours 😉 

It is not the same: in order to use payment intents with NuveiAch, you need to use create order and not create session.

Another difference is that this one adds tests, and maybe there was some miscommunication, but we were supposed to add these as gems, and not into our own repository.

**Comment by patrickclery** [comment]
By the way, I agree that now that we see you created a library with basically the same functions we could merges together, but that's a task for later and not something that we knew at the time.

**Comment by patrickclery** [comment]
closed - these changes were merged in d6a98424166ecbcdc75df0669131aa3045b29724 because at the same time @VergunDA was adding this to our main repo in the /lib folder, which ultimately was a better solution. https://github.com/Lexop/lexop/commit/702b62aabb071e4260276b7b369193f0437cadbc

**Pull request closed without merging**
